name: C/C++ Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyse:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        depth: 1
        submodules: 'recursive'
    - name: cppcheck-runtest
      uses: dreygur/cppcheck@main
      with:
        path: './dreg'
        enabled checks: all
        enable inconclusive: true
        verbose: true
        