name: C/C++ Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyse:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - run: mkdir -p output
    - name: Run Cppcheck
      uses: Bedzior/run-cppcheck@v1.0.0
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
        path: '.'
        verbose: true
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: output
    - name: cppcheck-runtest
      uses: dreygur/cppcheck@main
      with:
        path: '.'
        enabled checks: all
        enable inconclusive: true
        verbose: true
