name: C/C++ Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Run static analysis for C++ project
      uses: JacobDomagala/StaticAnalysis@v0.0.3
